name: taskati
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter_svg: ^2.2.0  
  flutter:
    sdk: flutter
  gap: ^3.0.1
  lottie: ^3.3.1
  image_picker: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  date_picker_timeline: ^1.2.7
  day_night_time_picker: ^1.3.1
  date_cupertino_bottom_sheet_picker: ^0.1.0



dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
<<<<<<< HEAD
  build_runner: ^2.4.13
=======
  build_runner: ^2.5.4
>>>>>>> 4b8a54fa885adb67a693824e7fd27b83c9cc86a3
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins0
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
